### ISSUE TITLE
ERROR! Invalid collection name - must be in the format <namespace>.<collection>

### ISSUE THREAD

**Issue by TinajaLabs** [Icinga/ansible-collection-icinga#101]
From mac Monterey - 12.2.1

```
# python3 -m pip show ansible
Name: ansible
Version: 6.2.0
```

```
# ansible --version
ansible 2.9.0
```

```
# ansible-galaxy collection install git+https://github.com/Icinga/ansible-collection-icinga.git,0.1.0
Process install dependency map
ERROR! Invalid collection name 'git+https', name must be in the format <namespace>.<collection>.
```

**Comment by TinajaLabs** [comment]
```ansible-galaxy 2.9.0```

**Comment by TinajaLabs** [comment]
Or pull the collection from the git. **(Only useable with Ansible version 2.10.9)** 

The above command copied from the main readme.  This note on the Getting started page...

_nevermind..._

**Comment by mkayontour** [comment]
Hi, sorry for the confusion and yes this is correct. I updated the README to provide the simple commands. And further information can be found on the getting started page. 

Thanks for pointing it out ;) If there's more or more detailed information missing, don't hesitate to open another issue.
