### ISSUE TITLE
icinga2_cert_path does not exist when providing ssl_key, ssl_cert and ssl_cacert to api feature

### ISSUE THREAD

**Issue by handy675** [Icinga/ansible-collection-icinga#132]
When running a playbook with feature api and providing ssl_key, ssl_cert and ssl_cacert, the playbook ends with error, that the icinga2_cert_path does not exists.

    icinga2_features:
      - name: api
        ssl_cert: "icinga2/certs/{{ ansible_fqdn }}.crt"
        ssl_key: "icinga2/certs/{{ ansible_fqdn }}.key"
        ssl_cacert: "icinga2/certs/ca.crt"

TASK [icinga.icinga.icinga2 : pre generated certificates copy to icinga2 certs] *************************************************************************************************************
failed: [ansitest.mstep] (item={'src': 'icinga2/certs/ca.crt', 'dest': '/var/lib/icinga2/certs/ca.crt'}) => {"_crt": {"dest": "/var/lib/icinga2/certs/ca.crt", "src": "icinga2/certs/ca.crt"}, "ansible_loop_var": "_crt", "changed": false, "checksum": "675b6c3211f4434dde8cd0a21aa8c99cd0b72272", "msg": "Destination directory /var/lib/icinga2/certs does not exist"}
failed: [ansitest.mstep] (item={'src': 'icinga2/certs/ansitest.mstep.key', 'dest': '/var/lib/icinga2/certs/ansitest.mstep.key'}) => {"_crt": {"dest": "/var/lib/icinga2/certs/ansitest.mstep.key", "src": "icinga2/certs/ansitest.mstep.key"}, "ansible_loop_var": "_crt", "changed": false, "checksum": "2e1f82956ccb28a6adc6c6c22d9c35d7f6a6f9db", "msg": "**Destination directory /var/lib/icinga2/certs does not exist**"}
failed: [ansitest.mstep] (item={'src': 'icinga2/certs/ansitest.mstep.crt', 'dest': '/var/lib/icinga2/certs/ansitest.mstep.crt'}) => {"_crt": {"dest": "/var/lib/icinga2/certs/ansitest.mstep.crt", "src": "icinga2/certs/ansitest.mstep.crt"}, "ansible_loop_var": "_crt", "changed": false, "checksum": "957d35bc858cc48ba4f1ab979d27fed6548ada98", "msg": "**Destination directory /var/lib/icinga2/certs does not exist**"}

I fixed it by adding task to create icinga2_cert_path in the block **use self provided certificates** in **icinga/icinga/roles/icinga2/tasks/features/api.yml** before copying the certificates.:

    - name: create cert directory
      file:
        path: "{{ icinga2_cert_path }}"
        state: directory
        mode: '0755'
        owner: root
        group: root

**Comment by martialblog** [comment]
Thanks for the hint, I'll have a look at it

**Comment by mkayontour** [comment]
Thanks for the Issue, it is now fixed and will be in the next release.
