### ISSUE TITLE
Add documentation for templates

### ISSUE THREAD

**Issue by Crited** [Icinga/ansible-collection-icinga#156]
Even though the option exists to create objects as [templates](https://github.com/Icinga/ansible-collection-icinga/blob/98392d6f19b47f88eae64d7aa082b2563bdedc54/molecule/default/host_vars/icinga-default.yaml#L52) instead, there is no documentation in [objects.md](https://github.com/Icinga/ansible-collection-icinga/blob/main/doc/role-icinga2/objects.md)

I suggest, that there should either be mention of that in objects.md or a seperate templates.md to explain that feature.

**Comment by martialblog** [comment]
Hi, makes sense. 

Do you want to open a PR?
