### ISSUE TITLE
ERROR! the role 'icinga.icinga.icingadb' was not found

### ISSUE THREAD

**Issue by MarcusCaepio** [Icinga/ansible-collection-icinga#168]
Hi again,
the currently available version of the collection provided by ansible-galaxy does not know icingadb*
`ERROR! the role 'icinga.icinga.icingadb' was not found`
But I would really like to setup an IcingaDB setup :) When will the new version available?

Cheers,
Marcus

**Comment by mkayontour** [comment]
Hi, I'll try to get the new version out this or next week, I wanted to do some more tests. If you want to test the collection and give feedback, you can install the collection via git and reference the main branch. https://docs.ansible.com/ansible/devel/collections_guide/collections_installing.html#installing-a-collection-from-a-git-repository-at-the-command-line
