### ISSUE TITLE
Configurable Icinga 2 Version

### ISSUE THREAD

**Issue by tbauriedel** [Icinga/ansible-collection-icinga#170]
As I see it, the installation of [Icinga 2](https://github.com/Icinga/ansible-collection-icinga/blob/main/roles/icinga2/tasks/install_on_Debian.yml#L4) is drilled to the latest available version.
To bring more flexibility, the versions should be configurable.

**Comment by lbetz** [comment]
Please don't, that is the task of a software management solution.

Otherwise, all dependent packages must be managed in the version, e.g. icinga2-common, icinga2-bin icinge2-*.

**Comment by tbauriedel** [comment]
With the use of a variable in the installation, the version could install only `icinga2` by default. This is already done in [role-icingaweb2](https://github.com/Icinga/ansible-collection-icinga/blob/main/roles/icingaweb2/tasks/install_on_debian.yml#L2).
If the user needs it for something else, he could fill the variable as he wishes.

I can think of several scenarios where you have to install a certain version of the products.
From my point of view, the whole thing would make perfect sense. If that does not correspond to what the Collection wants to represent, then so be it.

**Comment by lbetz** [comment]
You do not understand my point. If we do so, we have to handle all packages! And not only one for icinga2, one vor icingaweb2 and so on.

**Comment by tbauriedel** [comment]
I think it's exactly the other way around ;) 

If the roles remain true to the latest, this very thing does not have to be done. By default, only `icinga2` should be specified for the latest.

If the user wants to use a different version, he simply has to adapt the packages himself and observe the dependencies.

Exactly so it is currently also within the icingaweb2 role. 
`icingaweb2_packages: ["icingaweb2", "icingacli", "libapache2-mod-php"]`
Now if I want to install a different version, I can simply customize the packages and pin the version. And yes, then it is necessary to pin the dependencies as well. But this is then the responsibility of the user.

**Comment by lbetz** [comment]
Ok, that mean, we need a variable like icinga2_manage_package as Boolean to manage package or not?

**Comment by tbauriedel** [comment]
It wouldn't even need something like that.
The following would already be enough (I take as an example debian):

vars:
`icinga2_packages: ["icinga2"]`

install.yml:
```
- name: Install Icinga 2
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: True
  loop: "{{ icinga2_packages }}"
```

More would not be needed.
Thus, we remain true to the fact that by default the last version stable version is installed.
But if someone needs a different version, he can adjust the packages in his playbook.

**Comment by widhalmt** [comment]
I see you both having a point. I'm with @lbetz that having software management do the installation is the right way to do it. But just like @tbauriedel I see that many users only use Ansible and don't even use software management any more. And when there's a need for a specific version, they have to rely on Ansible.

My approach is usually to have have a version variable without a default. When it's set, then Ansible will install this specific if not, it will install the latest available. But it will not update by default. Offering updates via Ansible is something different, yet. And I'm not sure if I like it or not with leaning to "not".

There's a solution to that problem in https://github.com/NETWAYS/ansible-collection-elasticstack/blob/main/roles/logstash/tasks/main.yml#L54-L78 . Given, that's ugly and complicated but according to our tests it works.

**Comment by lbetz** [comment]
@tbauriedel using a loop mean, you will have e.g. on red hat with yum a single yum/dnf exec for each package. If you use package names with versions that will fail, because icinga-2-2.13.8 will lookup for icinga2-bin, will find 2.14.0 and boom.

**Comment by tbauriedel** [comment]
Good point. I forgot this.

With `ansible.builtin.yum`, `ansible.builtin.apt` and `community.general.zypper` you can provide a list of packages without looping trough.

In detail, it would look like this:
```
- name: Apt - install package icinga2
  ansible.builtin.apt:
    name: "{{ icinga2_packages }}"
    state: present
```

If you want, I can create a PR for this. Just let me know

**Comment by widhalmt** [comment]
Yes, please don't use a loop with `package`, `yum` or `apt`.
