### ISSUE TITLE
[Icingaweb2] ints in icingaweb2_config shall be strings

### ISSUE THREAD

**Issue by MisterMountain** [Icinga/ansible-collection-icinga#178]
Inside the icingaweb2_config's default vars are 2 integers, that shall be strings to work properly:
`    show_stacktraces: 1
    show_application_state_messages: 1
`
If you put them into doublequotes everything's fine.

**Comment by martialblog** [comment]
Hi, do you want to open a PR for that?

**Comment by MisterMountain** [comment]
Yeah sure, that ain't a big deal ;) 
@martialblog

**Comment by mkayontour** [comment]
Should be fixed within the template, otherwise other will run into issues while using the role.

```
{% if variable is number %} test {% endif %}
```

**Comment by mkayontour** [comment]
@MisterMountain Can you verify if it works in your environment with the changes from #183 ?

**Comment by mocdaniel** [comment]
Verified fix via #183
