### ISSUE TITLE
icingadb role doesn't create the db user or database

### ISSUE THREAD

**Issue by tomkivlin** [Icinga/ansible-collection-icinga#185]
This may be my misunderstanding, but I expected the icingadb role to also create the database user and the database - e.g. the first couple of steps here: https://icinga.com/docs/icinga-db/latest/doc/02-Installation/06-Ubuntu/#setting-up-the-database

I found that I had to perform those steps outside of the provided roles, and then run the playbook again to get the schema import to work.

This is a feature request to either include the user/database creation as part of the role or to include something in the documentation to explain that the steps in the above page need to be done first.

Thanks!

**Comment by tomkivlin** [comment]
I also found this with the icingaweb2 role.  Again, no preference either way but would be handy to know if outside steps are needed.

**Comment by mkayontour** [comment]
Hi, we won't include the creation of the database in the role as you mentioned. We would recommend to use the popular roles available. 

You're right that we should include information about the handling of the database and which roles are maybe available to use, just a quick guide how to succeed ;) 

I'll get to it this week. Thanks for the hint!

**Comment by mocdaniel** [comment]
Took us a bit longer to add, but there's a PR in #216 now, in case you want to have a look already :)
