### ISSUE TITLE
General: Collection should be able to handle updates

### ISSUE THREAD

**Issue by mocdaniel** [Icinga/ansible-collection-icinga#204]
Consider the following:

You installed Icinga manually to try things out, and now you're using the collection to roll out a proper setup. In those situations, the collection doesn't report that some packages might've been already installed, but **doesn't upgrade** them either, which might result in unexpected versions being installed, e.g. huge skews between `icinga2` and `icingaweb2` versions.

Proposed fix:

Allow an explicit version of each package to be installed, and default to an installation/update of/to the most up-to-date version of the package in question otherwise.

**Comment by mkayontour** [comment]
Hey, 

I know the issue, I wouldn't advise to let the collection handle updates in the general installation process. I know it's a hassle if there's pre installed packages. But we are focusing on fresh automated setups. 

In generell we already had the discussion on package version in issue #170, you can define the packages in extra variables. 

Example for APT
```
APT: 
icinga2_packages: ["icinga2=2.14.0"]
YUM: 
icinga2_packages: ["icinga2-2.14.0-1.el7"]
```

For upgrades there should be a playbook where specific upgrade tasks should be handled in addition. Migration of DB and so  on.

**Comment by mocdaniel** [comment]
I agree - I didn't know it was possible to define specific package versions this way. This is totally fine imo, so I will go ahead and close this issue for now.
