### ISSUE TITLE
ini_template is not working for advanced ldap filters.

### ISSUE THREAD

**Issue by rolatsch** [Icinga/ansible-collection-icinga#208]
The ini_templates uses the `quote` filter for all strings containing =. This breaks when you try to configure a ldap filter like `!(objectClass=computer)` or anything containing parentheses is rendered as `"'(objectClass=computer)'"`.

https://github.com/Icinga/ansible-collection-icinga/blob/a71267ddff82503ee1ab009ce1ce211d2c5c3200/roles/icingaweb2/templates/ini_template.j2#L11C1-L11C37

**Comment by mkayontour** [comment]
Hello, I'll have a look into it. How did you define the variable in yaml? Can you give a example?

**Comment by rolatsch** [comment]
Sure, i tried every way i could think of.
`user_filter: "!(objectClass=user)"`, `user_filter: '!(objectClass=user)'`, 
```
user_filter: >
  !(objectClass=user)
```
```
user_filter: |
  !(objectClass=user)
```

But the problem is in the template. `"{{ value | quote }}"`. The print expression is wrapped into double quotes and uses the quote filter which adds additional single quotes.

**Comment by a2yp** [comment]
I came across this problem today. Is there a plan when the fix will be released?
