### ISSUE TITLE
install_on_suse.yml not found for role icinga.icinga.icingadb

### ISSUE THREAD

**Issue by johanneskastl** [Icinga/ansible-collection-icinga#231]
Is it intentional that there is no `install_on_suse.yml` file in the icinga.icinga.icingadb role?

https://github.com/Icinga/ansible-collection-icinga/blob/main/roles/icingadb/tasks/main.yml#L16

```
- name: Include OS specific installation
  ansible.builtin.include_tasks: "install_on_{{ ansible_os_family | lower }}.yml"
```

If so, the role should fail and report, that the installation on SUSE/openSUSE is not (yet) supported.

**Comment by mkayontour** [comment]
This should be somehow stated when running on unsupported os. But haven't got the time to implement any support. Open for any contributions if possible ;)

**Comment by johanneskastl** [comment]
Thanks for the fast reply. I'll see if I can implement this.
