### ISSUE TITLE
Add support for Suse System

### ISSUE THREAD

**Issue by mkayontour** [Icinga/ansible-collection-icinga#259]
To fully support Suse, the following tasks need to be done. 
- [x] Add support in role icinga2
- [x] Add support in role icingadb
- [x] Add support in role icingadb_redis
- [x] #271
- [x] Add support in role repos
- [x] Add support in role monitoring_plugins
- [x] Document zypper requirements for OS Suse
- [x] Add to galaxy.yml

Ref PR #237 #236 #235 #234 #233 #328

**Comment by Donien** [comment]
Closing as per last PR (monitoring plugins).
