### ISSUE TITLE
icingadb role doesn't accomodate `icingadb_database_port` when importing schema

### ISSUE THREAD

**Issue by glbyers** [Icinga/ansible-collection-icinga#267]
The schema import task (roles/icingadb/tasks/manage_schema_mysql.yml) does not honour the icingadb_database_port role parameter. Whilst it's not common to override mysqld port, it is more common to run something like proxysql in front, which uses it's own port.

**Comment by mkayontour** [comment]
Thanks for reporting the issue. Somehow forgot to put it in there :D
