### ISSUE TITLE
Hardcoded Variables in Tasks

### ISSUE THREAD

**Issue by Saeid-Abadi** [Icinga/ansible-collection-icinga#270]
In following task some variables are hardcoded defined, In this case if you set one of the variables for example in group_vars it will be overwrited bei roll out, if you import roles one after other:
roles:
    - icinga.icinga.repo
    - icinga.icinga.monitoring_plugins

https://github.com/Icinga/ansible-collection-icinga/blob/61d19c6a5490ca370eeb616167cd92da8ca1c91f/roles/monitoring_plugins/tasks/install_on_RedHat.yml#L3C1-L12C1

**Comment by mkayontour** [comment]
Will be fixed in the next version. Thanks for the issue.
