### ISSUE TITLE
Bugfix without new release

### ISSUE THREAD

**Issue by lucagubler** [Icinga/ansible-collection-icinga#283]
Hi team

3 months ago you released v0.3.3. That's the version I installed from Ansible Galaxy. Unfortunately I ran into an issue when I want to define global objects and install them across every host. This was fixed here https://github.com/Icinga/ansible-collection-icinga/pull/255 but I think this commit didn't make it into v0.3.3

Is it possible that you create a new release for Ansible Galaxy that includes this (and maybe other) bugfixes?

Thanks
Luca

**Comment by mkayontour** [comment]
Hello, sorry for the wait - as I'm not primarily working on the collection I didn't got the time to sort out a new release. 

I try to get a new release before the summit - at least with a few fixes. 

Sorry in advance.

**Comment by mkayontour** [comment]
It is out now! Finally!
