### ISSUE TITLE
IcingaDB Redis package does not create log directory

### ISSUE THREAD

**Issue by Donien** [Icinga/ansible-collection-icinga#298]
There has been a change in the newest packages of IcingaDB Redis provided over packages.icinga.com.

`/var/log/icingadb-redis` is no longer created. Information will now be logged to Systemd by default which seems to be the reason why the directory is no longer created by default.

The configuration template still sets the variable for the log directory.  
We'd need to either omit it or create the directory within the Ansible code to make sure the service can even start.  

(One) affected version of the package (look in `postinst` script):
[icingadb-redis-tools_7.0.15-1+ubuntu20.04_all.deb](https://packages.icinga.com/ubuntu/pool/main/i/icingadb-redis/icingadb-redis-tools_7.0.15-1+ubuntu20.04_all.deb)

Still working version:  
[icingadb-redis-tools_7.0.12-1+ubuntu20.04_amd64.deb](https://packages.icinga.com/ubuntu/pool/main/i/icingadb-redis/icingadb-redis-tools_7.0.12-1+ubuntu20.04_amd64.deb)

**Comment by mkayontour** [comment]
I would create the directory, to ensure it is available even if it is not used. I guess you could still change it to write to file?
