### ISSUE TITLE
icinga2_custom_config not working with files in subfolders...

### ISSUE THREAD

**Issue by telution** [Icinga/ansible-collection-icinga#309]
If you use a subfolder it breaks ansible because the slashed / are not replaced: 

icinga2_custom_config:
  - name: someFolder/myown_command.conf
    path: zones.d/main/myown_command.conf
    order: 10

    - name: add custom config to assemble
      ansible.builtin.copy:
        owner: root
        group: root
        src: "files/{{ item.name }}"
        **dest: "{{ icinga2_fragments_path }}/{{ item.path }}/{{ item.order|default('20')|string }}_{{ item.name }}"**
      loop: "{{ icinga2_custom_config }}"

**Comment by Donien** [comment]
Hey,

I implemented and tested a [fix](#313) which LGTM. Just waiting for more eyes to confirm.

Thank you for letting us know!
