### ISSUE TITLE
Add role to manage icingaweb2

### ISSUE THREAD

**Issue by lbetz** [Icinga/ansible-collection-icinga#31]

**Comment by l00ptr** [comment]
I have such role for my own project; it's not already published, if you wan i can try to create a merge request based on this role and how you write your collection. Please let me know if you are already working on this issue!

**Comment by martialblog** [comment]
Hi, at the moment we don't have anything concrete for the icingaweb2 role. If you have some code to share, feel free to open a PR and we'd be happy to review it and get it merged

**Comment by l00ptr** [comment]
started a new MR to implement this, it's still a draft but do not hesitate to share some feedback there #149
