### ISSUE TITLE
Prepare a concept to test roles, plugins and icinga2parser

### ISSUE THREAD

**Issue by lbetz** [Icinga/ansible-collection-icinga#32]

**Comment by lbetz** [comment]
Documentation for every feature, object and role variable. Files under docs.

**Comment by lbetz** [comment]
Create single issues for every feature and object type, also for every role.

**Comment by lbetz** [comment]
notification scripts have to manage yourself

**Comment by mkayontour** [comment]
Issue is finished: 

* Documentation for Features, Parser and Roles are done
* Tests are enabled for PR and main 
* Unittest for parser
* Test for Ansible version 2.9, 2.10, 2.11 active
