### ISSUE TITLE
Extend icinga2_confd to use also a path to include in config

### ISSUE THREAD

**Issue by lbetz** [Icinga/ansible-collection-icinga#33]

**Comment by lbetz** [comment]
example:

icinga2_confd: yes (=> include_recursive "conf.d")
icinga2_confd: local.d (=> include_recursive "local.d")

**Comment by mkayontour** [comment]
three possibilities are available:

`icinga2_confd: false` disables conf.d
`icinga2_confd: yes` includes conf.d 
`icinga2_confd: local.d` includes named folder recursive
