### ISSUE TITLE
Add `check-and-reload` or `check-and-restart` handler

### ISSUE THREAD

**Issue by lucagubler** [Icinga/ansible-collection-icinga#347]
When managing Icinga2 objects with Ansible, the configuration is defined in YAML and then parsed into the Icinga2 DSL. However, after these objects are configured, the Ansible playbook triggers a `restart` or `reload` handler for Icinga2. If the configuration has any issues, this approach results in Icinga2 attempting to reload, potentially leading to a broken or non-functional state.

The current `restart` or `reload` handler does not verify the validity of the configuration before applying it. This can lead to a situation where Icinga2 is reloaded with invalid configuration, causing service disruptions.

Add a new handler, `check-and-reload` or `check-and-restart`, to validate the Icinga2 configuration before applying it. This handler would perform the following steps:
- Validate the Configuration by running `icinga2 daemon --validate` to check if the configuration is valid.
  - If the exit code is 0, the configuration is valid, and it is safe to proceed with restarting or reloading Icinga2.
  - If the exit code is not 0, the configuration has errors. In this case, skip the restart/reload and leave Icinga2 running with the current, last-known-good configuration.

**Comment by mkayontour** [comment]
Icinga 2 should check it's configuration before reloading by default. I'll check if we restart the core everytime we deploy configuration.
