### ISSUE TITLE
Use code from existing Collection?

### ISSUE THREAD

**Issue by schmitmd** [Icinga/ansible-collection-icinga#4]
I just figured I'd point out that someone has already written a decent enough (on the surface anyway) collection for Icinga.  https://github.com/fiaasco/icinga2 .  Perhaps you could contact the dev and ask to import some of their code instead of (re)writing from scratch?

**Comment by mkayontour** [comment]
Hello @schmitmd, thanks for pointing the collection out, I'll have look.

In general it would be a good thing to reuse some code. But we try to get everything rewritten to achieve a certain goal. The main goal is to generate configuration mainly from the new parser. This set, any Icinga instance can then configured with this mechanism and therefore we can't reuse the existing code. 

I'll close this issue.

**Comment by mkayontour** [comment]
Sorry for closing the issue so fast! Hope this does answer your question.

**Comment by schmitmd** [comment]
It's all good.  My only outstanding question is if y'all are planning on adding postgres support to the collection.  As far as I can tell, no existing collections are set up to work w/ pgsql-ido.
