### ISSUE TITLE
RHEL/Centos: manage icinga2-selinux package

### ISSUE THREAD

**Issue by ogajduse** [Icinga/ansible-collection-icinga#40]
I hit [this](https://github.com/Icinga/icinga2/issues/7832) problem after the first `icinga2` role run. I resolved it by installing the `icinga2-selinux` package. I recommend installing `icinga2-selinux` by default in the same dnf transaction as the `icinga2` package.
Note that installing the `icinga2-selinux` as a pre-task is not an option as it has a dependency on the base `icinga2` package.
```
# rpm -qR icinga2-selinux | grep el8\.icinga
icinga2-bin = 2.12.3-1.el8.icinga
```

**Comment by mkayontour** [comment]
hi @ogajduse thanks for the report. Yes indeed that is missing, we need to discuss if it should be installed by default. But we will definitely provide a variable to enable or disable this behaviour.

**Comment by ogajduse** [comment]
@lbetz Thanks for the patch!
