### ISSUE TITLE
Argument clean up results in fatal based on set_fact with argument 'None'

### ISSUE THREAD

**Issue by Crited** [Icinga/ansible-collection-icinga#49]
The api feature ran into an error on cleanup. This is probably caused by previous features using set_fact to set the string 'None', which can't be combined in:
 https://github.com/Icinga/ansible-collection-icinga/blob/e51f7fc1f822ccb4d770b564266198cb893c25c4/roles/icinga2/tasks/features/api.yml#L23

Which results in:
```
TASK [icinga2 : api feature cleanup arguments list] *****************************************************
fatal: [***.org]: FAILED! => {"msg": "|combine expects dictionaries, got 'None'"}
```

The occurences of set_fact in 91b7635ce07786425020629f3724d18faf71a3ec should be changed to `{}` instead of _None_ / 'None'

**Comment by lazyfrosch** [comment]
This should be fixed by #51 and is a Ansible 2.9 issue
